content:
  - name: projects
    label: Projects
    path: src/content/projects
    filename: "{fields.title}.md"
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: technologies
        label: Technologies Used
        type: list
      - name: url
        label: Project URL
        type: string
      - name: image
        label: Project Image
        type: image
      - name: featured
        label: Featured Project
        type: boolean
      - name: body
        label: Details
        type: rich-text

  - name: site-settings
    label: Site Settings
    path: src/config/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: text
      - name: author
        label: Author Name
        type: string
      - name: socialLinks
        label: Social Links
        type: object
        fields:
          - name: github
            label: GitHub URL
            type: string
          - name: linkedin
            label: LinkedIn URL
            type: string
          - name: twitter
            label: Twitter URL
            type: string

  - name: about
    label: About Page
    path: src/content/about.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: image
        label: Profile Image
        type: image
      - name: body
        label: About Content
        type: rich-text

media:
  input: public/media
  output: /media
