media:
  - name: images
    label: Images
    input: public/media
    output: /media
    categories: [image]
    extensions: [jpg, jpeg, png, webp]

content:
  - name: site
    label: Site Settings
    path: src/config/site.json
    type: file
    fields:
      - name: title
        label: Site Title
        type: string
        required: true
      - name: description
        label: Site Description
        type: string
        required: true
      - name: author
        label: Author Name
        type: string
        required: true
      - name: homeHeadshot
        label: Homepage Profile Image
        type: image
        description: The profile image shown on the homepage (128x128px circular)
      - name: socialLinks
        label: Social Media Links
        type: object
        fields:
          - name: github
            label: GitHub URL
            type: string
          - name: linkedin
            label: LinkedIn URL
            type: string
          - name: twitter
            label: Twitter URL
            type: string

  - name: about
    label: About Page
    path: src/content/about.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: string
        required: true
      - name: description
        label: Page Description
        type: string
        required: true
      - name: image
        label: About Page Image
        type: image
        description: The profile image shown on the about page
      - name: body
        label: Content
        type: rich-text

  - name: projects
    label: Projects
    path: src/content/projects
    type: collection
    fields:
      - name: title
        label: Project Title
        type: string
        required: true
      - name: description
        label: Project Description
        type: string
        required: true
      - name: technologies
        label: Technologies Used
        type: string
        list: true
      - name: url
        label: Project URL
        type: string
      - name: image
        label: Project Image
        type: image
      - name: featured
        label: Featured Project
        type: boolean
        default: false
      - name: date
        label: Project Date
        type: date
      - name: body
        label: Content
        type: rich-text
