collections:
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: text
      - name: technologies
        label: Technologies
        widget: map
        key_label: Technology Name
        value_label: Description
        hint: "Add technologies used in this project with descriptions"
      - name: url
        label: Project URL
        widget: string
        required: false
      - name: image
        label: Project Image
        widget: image
        required: false
      - name: featured
        label: Featured
        widget: boolean
        default: false
      - name: date
        label: Date
        widget: datetime
        required: false
      - name: content
        label: Content
        widget: markdown
        required: false

  - name: settings
    label: Settings
    files:
      - name: site
        label: Site Settings
        file: src/config/site.json
        fields:
          - name: title
            label: Site Title
            widget: string
          - name: description
            label: Site Description
            widget: string
          - name: author
            label: Author Name
            widget: string
          - name: socialLinks
            label: Social Links
            widget: object
            fields:
              - name: github
                label: GitHub URL
                widget: string
              - name: linkedin
                label: LinkedIn URL
                widget: string
              - name: twitter
                label: Twitter URL
                widget: string
